# Generated by Django 5.1.1 on 2024-09-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoclasses',
            name='title',
            field=models.CharField(choices=[('Django for Beginners', 'Django for Beginners'), ('Data Science Fundamentals', 'Data Science Fundamentals'), ('Intro to Python', 'Intro to Python')], max_length=60),
        ),
    ]
